# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited', models.BooleanField()),
                ('comments', models.CharField(max_length=280)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=200)),
                ('resource_url', models.CharField(max_length=300)),
                ('resource_description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='favorite',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stractic.Resource'),
        ),
    ]
